// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SL.DesafioPagueVeloz.Infrastructure.Persistence.Context;

#nullable disable

namespace SL.DesafioPagueVeloz.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SL.DesafioPagueVeloz.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("IX_Clientes_Ativo");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Clientes_Email");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("SL.DesafioPagueVeloz.Domain.Entities.Conta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("LimiteCredito")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("SaldoDisponivel")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoReservado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("IX_Contas_ClienteId");

                    b.HasIndex("Numero")
                        .IsUnique()
                        .HasDatabaseName("IX_Contas_Numero");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Contas_Status");

                    b.ToTable("Contas", (string)null);
                });

            modelBuilder.Entity("SL.DesafioPagueVeloz.Domain.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConteudoJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErroProcessamento")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("Processado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ProcessadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProximaTentativaEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("TentativasProcessamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Processado")
                        .HasDatabaseName("IX_OutboxMessages_Processado");

                    b.HasIndex("ProximaTentativaEm")
                        .HasDatabaseName("IX_OutboxMessages_ProximaTentativaEm")
                        .HasFilter("[ProximaTentativaEm] IS NOT NULL");

                    b.HasIndex("Processado", "CriadoEm")
                        .HasDatabaseName("IX_OutboxMessages_Processado_CriadoEm");

                    b.HasIndex("Processado", "TentativasProcessamento")
                        .HasDatabaseName("IX_OutboxMessages_Processado_Tentativas");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("SL.DesafioPagueVeloz.Domain.Entities.Transacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ContaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MotivoFalha")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ProcessadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<Guid?>("TransacaoOrigemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ContaId")
                        .HasDatabaseName("IX_Transacoes_ContaId");

                    b.HasIndex("CriadoEm")
                        .HasDatabaseName("IX_Transacoes_CriadoEm");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("IX_Transacoes_IdempotencyKey");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Transacoes_Status");

                    b.HasIndex("TransacaoOrigemId")
                        .HasDatabaseName("IX_Transacoes_TransacaoOrigemId");

                    b.HasIndex("ContaId", "CriadoEm")
                        .HasDatabaseName("IX_Transacoes_ContaId_CriadoEm");

                    b.ToTable("Transacoes", (string)null);
                });

            modelBuilder.Entity("SL.DesafioPagueVeloz.Domain.Entities.Cliente", b =>
                {
                    b.OwnsOne("SL.DesafioPagueVeloz.Domain.ValueObjects.Documento", "Documento", b1 =>
                        {
                            b1.Property<Guid>("ClienteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(14)
                                .HasColumnType("varchar(14)")
                                .HasColumnName("Documento");

                            b1.Property<int>("Tipo")
                                .HasColumnType("int")
                                .HasColumnName("TipoDocumento");

                            b1.HasKey("ClienteId");

                            b1.HasIndex("Numero")
                                .IsUnique()
                                .HasDatabaseName("IX_Clientes_Documento");

                            b1.ToTable("Clientes");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");
                        });

                    b.Navigation("Documento")
                        .IsRequired();
                });

            modelBuilder.Entity("SL.DesafioPagueVeloz.Domain.Entities.Conta", b =>
                {
                    b.HasOne("SL.DesafioPagueVeloz.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Contas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("SL.DesafioPagueVeloz.Domain.Entities.Transacao", b =>
                {
                    b.HasOne("SL.DesafioPagueVeloz.Domain.Entities.Conta", "Conta")
                        .WithMany("Transacoes")
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conta");
                });

            modelBuilder.Entity("SL.DesafioPagueVeloz.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Contas");
                });

            modelBuilder.Entity("SL.DesafioPagueVeloz.Domain.Entities.Conta", b =>
                {
                    b.Navigation("Transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
